@startuml

title __Utilities Class Diagram__\n

  namespace com.fyp {
    namespace helper {
      class com.fyp.helper.FaceDetectorHelper {
          {static} + FACE_RECT_COLOR : Scalar
          {static} + FONT_COLOR : Scalar
          {static} - TAG_CASCADE : String
          {static} - TAG_YUNET : String
          {static} + LoadFaceDetectorYN()
          {static} + loadClassifier()
      }
    }
  }
  

  namespace com.fyp {
    namespace helper {
      class com.fyp.helper.FrameFlipHelper {
          {static} + FlipRotateFrameHorizental()
      }
    }
  }
  

  namespace com.fyp {
    namespace helper {
      class com.fyp.helper.GetDistanceUtils {
          {static} - EARTH_RADIUS : int
          {static} + distanceInKm()
          {static} + distanceInMi()
          {static} + getDistance()
          {static} - rad()
      }
    }
  }
  


  

  namespace com.fyp {
    namespace helper {
      class com.fyp.helper.QRCodeHelper {
          {static} + createQRCodeBitmap()
          {static} + createQRCodeBitmap()
      }
    }
  }
  

  namespace com.fyp {
    namespace helper {
      class com.fyp.helper.QRCodeHelper.QRInformation {
          - LectureID : String
          - LectureName : String
          - Lecturer : String
          - date : String
          - latitude : double
          - lecturerID : String
          - longitude : double
          - venue : String
          + getDate()
          + getLatitude()
          + getLectureID()
          + getLectureName()
          + getLecturer()
          + getLecturerID()
          + getLongitude()
          + getVenue()
          + setDate()
          + setLatitude()
          + setLectureID()
          + setLectureName()
          + setLecturer()
          + setLecturerID()
          + setLongitude()
          + setVenue()
      }
    }
  }
  

  com.fyp.helper.QRCodeHelper +-down- com.fyp.helper.QRCodeHelper.QRInformation


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
